# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11Va-DersQcF-9EOB0UxwfcMjbyfNnwCZ

1. Creating the Knowledge Base

initial state
"""

from aima3.logic import FolKB
from aima3.utils import expr

kb = FolKB([
      expr('At(Wolf, Left)'),
      expr('At(Sheep, Left)'),
      expr('At(Cabbage, Left)'),
      expr('At(Farmer, Left)'),
      expr('NotAt(Wolf, Right)'),
      expr('NotAt(Sheep, Right)'),
      expr('NotAt(Cabbage, Right)'),
      expr('NotAt(Farmer, Right)')
    ])

"""2. Adding New Information

"""

kb.tell(expr('At(Farmer, Left) & At(Sheep, Left) ==> At(Farmer, Right) & At(Sheep, Right)'))
kb.tell(expr('At(Farmer, Right) & At(Wolf, Right) ==> At(Farmer, Left) & At(Wolf, Left)'))

kb.tell(expr('Hates(Sheep, Wolf)'))
kb.tell(expr('Hates(Cabbage, Sheep)'))
kb.tell(expr('Hates(Farmer, Wolf)'))

"""3. Removing Information

"""

kb.retract(expr('Hates(Farmer, Wolf)'))

"""4. Querying the Knowledge Base

"""

is_safe = kb.ask(expr('Unsafe'))
print(is_safe)

kb.ask(expr('At(Farmer, Right) & At(Sheep, Left) ==> At(Farmer, Left) & At(Sheep, Right)'))

kb.ask(expr('Hates(Sheep,Cabbage)'))

"""Making Inferences

The power of a FOL KB lies in its ability to make inferences based on the rules and facts it contains. In this example, the KB can infer that current state is safe because it knows:
everybody is at the right side so there is no any unsafe condition.



"""